// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// colMax
NumericVector colMax(NumericMatrix X);
RcppExport SEXP _qcsim_colMax(SEXP XSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    rcpp_result_gen = Rcpp::wrap(colMax(X));
    return rcpp_result_gen;
END_RCPP
}
// colMin
NumericVector colMin(NumericMatrix X);
RcppExport SEXP _qcsim_colMin(SEXP XSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    rcpp_result_gen = Rcpp::wrap(colMin(X));
    return rcpp_result_gen;
END_RCPP
}
// cutoffContig
LogicalVector cutoffContig(NumericMatrix X, double cutoff, int contig);
RcppExport SEXP _qcsim_cutoffContig(SEXP XSEXP, SEXP cutoffSEXP, SEXP contigSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    Rcpp::traits::input_parameter< double >::type cutoff(cutoffSEXP);
    Rcpp::traits::input_parameter< int >::type contig(contigSEXP);
    rcpp_result_gen = Rcpp::wrap(cutoffContig(X, cutoff, contig));
    return rcpp_result_gen;
END_RCPP
}
// tftestMat
LogicalVector tftestMat(NumericMatrix X1, NumericMatrix X2, int useT, int useF, double tcutoff, double fcutofflow, double fcutoffhigh);
RcppExport SEXP _qcsim_tftestMat(SEXP X1SEXP, SEXP X2SEXP, SEXP useTSEXP, SEXP useFSEXP, SEXP tcutoffSEXP, SEXP fcutofflowSEXP, SEXP fcutoffhighSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type X1(X1SEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type X2(X2SEXP);
    Rcpp::traits::input_parameter< int >::type useT(useTSEXP);
    Rcpp::traits::input_parameter< int >::type useF(useFSEXP);
    Rcpp::traits::input_parameter< double >::type tcutoff(tcutoffSEXP);
    Rcpp::traits::input_parameter< double >::type fcutofflow(fcutofflowSEXP);
    Rcpp::traits::input_parameter< double >::type fcutoffhigh(fcutoffhighSEXP);
    rcpp_result_gen = Rcpp::wrap(tftestMat(X1, X2, useT, useF, tcutoff, fcutofflow, fcutoffhigh));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_qcsim_colMax", (DL_FUNC) &_qcsim_colMax, 1},
    {"_qcsim_colMin", (DL_FUNC) &_qcsim_colMin, 1},
    {"_qcsim_cutoffContig", (DL_FUNC) &_qcsim_cutoffContig, 3},
    {"_qcsim_tftestMat", (DL_FUNC) &_qcsim_tftestMat, 7},
    {NULL, NULL, 0}
};

RcppExport void R_init_qcsim(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
