# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

colMax <- function(X) {
    .Call(`_qcsim_colMax`, X)
}

colMin <- function(X) {
    .Call(`_qcsim_colMin`, X)
}

cutoffContig <- function(X, cutoff, contig) {
    .Call(`_qcsim_cutoffContig`, X, cutoff, contig)
}

tftestMat <- function(X1, X2, useT, useF, tcutoff, fcutofflow, fcutoffhigh) {
    .Call(`_qcsim_tftestMat`, X1, X2, useT, useF, tcutoff, fcutofflow, fcutoffhigh)
}

